spring.application.name=setupsDemo

spring.datasource.url=jdbc:oracle:thin:@//192.0.0.161:15226/MUTUAL
spring.datasource.username=TQ_LMS
spring.datasource.password=TQ_LMS
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.web.resources.add-mappings=false
spring.mvc.static-path-pattern=/static/**
spring.messages.always-use-message-format=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
security.basic.enable: false
security.ignored=/**
server.port=8070