package com.turnquest.setupsdemo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This table stores details of reinsurance transactions related to specific risks.
 */
@Entity
@Table(name = "GIN_POLICY_RISK_RI_DTLS")
@Data
public class GinPolicyRiskRiDtls {
    /**
 * Table Primary Key
 */
@Id
@Column(name = "PRRD_CODE", nullable = false, precision = 22)
private Long prrdCode;

/**
 * Foreign Reference to GIN_INSURED_PROPERTY_UNDS
 */
@Column(name = "PRRD_IPU_CODE", nullable = false, precision = 22)
private Long prrdIpuCode;

/**
 * Unique identifier autogenerated for the risk
 */
@Column(name = "PRRD_IDX", nullable = false, precision = 22)
private Long prrdIdx;

/**
 * Transaction number reference Key to GIN_GIS_TRANSACTIONS
 */
@Column(name = "PRRD_TRAN_NO", nullable = false, precision = 22)
private Long prrdTranNo;

/**
 * With effective from date
 */
@Column(name = "PRRD_WEF")
private Date prrdWef;

/**
 * With effective to date
 */
@Column(name = "PRRD_WET")
private Date prrdWet;

/**
 * Current reinsurance transaction indicator
 */
@Column(name = "PRRD_CURRENT", length = 1)
private String prrdCurrent;

/**
 * Company retention amount
 */
@Column(name = "PRRD_COMP_RETENTION", precision = 35, scale = 5)
private BigDecimal prrdCompRetention;

/**
 * Available excess amount to be ceded facultatively
 */
@Column(name = "PRRD_AVAIL_FULC_BAL", precision = 30, scale = 5)
private BigDecimal prrdAvailFulcBal;

/**
 * Gross company retention amount
 */
@Column(name = "PRRD_GROSS_COMP_RETENTION", precision = 35, scale = 5)
private BigDecimal prrdGrossCompRetention;

/**
 * Amount ceded to facre accounts
 */
@Column(name = "PRRD_FACRE_AMOUNT", precision = 30, scale = 5)
private BigDecimal prrdFacreAmount;

/**
 * Company retention rate
 */
@Column(name = "PRRD_COM_RETENTION_RATE", precision = 35, scale = 5)
private BigDecimal prrdComRetentionRate;

/**
 * Grouped risks Sum Insured percentage
 */
@Column(name = "PRRD_GRP_SI_RISK_PCT", precision = 35, scale = 5)
private BigDecimal prrdGrpSiRiskPct;

/**
 * Grouped risks top location amount
 */
@Column(name = "PRRD_GRP_TOP_LOC", precision = 35, scale = 5)
private BigDecimal prrdGrpTopLoc;

/**
 * Group risks company gross retention
 */
@Column(name = "PRRD_GRP_COMP_GROSS_RET", precision = 30, scale = 5)
private BigDecimal prrdGrpCompGrossRet;

/**
 * Group risks company net retention
 */
@Column(name = "PRRD_GRP_COMP_NET_RET", precision = 35, scale = 5)
private BigDecimal prrdGrpCompNetRet;

/**
 * Reinsurance premium
 */
@Column(name = "PRRD_RI_PREM", precision = 35, scale = 5)
private BigDecimal prrdRiPrem;

    /**
 * Excess percentage
 */
@Column(name = "PRRD_EXCESS_PCT", precision = 22, scale = 5)
private BigDecimal prrdExcessPct;

/**
 * Company retention rate
 */
@Column(name = "PRRD_COMP_NET_RATE", precision = 35, scale = 5)
private BigDecimal prrdCompNetRate;

/**
 * Prorata days
 */
@Column(name = "PRRD_PRORATA_DAYS", precision = 22)
private Long prrdProrataDays;

/**
 * Previous facre rate
 */
@Column(name = "PRRD_PREV_FACRE_RATE", precision = 22, scale = 5)
private BigDecimal prrdPrevFacreRate;

/**
 * Refund premium
 */
@Column(name = "PRRD_REFUND_PREM", precision = 22, scale = 5)
private BigDecimal prrdRefundPrem;

/**
 * Previous retention rate
 */
@Column(name = "PRRD_PREV_RET_RATE", precision = 22, scale = 5)
private BigDecimal prrdPrevRetRate;

/**
 * Previous net retention rate
 */
@Column(name = "PRRD_PREV_NET_RATE", precision = 22, scale = 5)
private BigDecimal prrdPrevNetRate;

/**
 * Date authorized
 */
@Column(name = "PRRD_AUTH_DT")
private Date prrdAuthDt;

/**
 * Facre rate
 */
@Column(name = "PRRD_FACRE_RATE", precision = 25, scale = 5)
private BigDecimal prrdFacreRate;

/**
 * Allowed gross company retention
 */
@Column(name = "PRRD_ALLOWED_GRS_COMP_RET", precision = 35, scale = 5)
private BigDecimal prrdAllowedGrsCompRet;

/**
 * Underwriting year
 */
@Column(name = "PRRD_AS_UWYR", precision = 5)
private Long prrdAsUwyr;

/**
 * Annual premium
 */
@Column(name = "PRRD_ANNUAL_PREM", precision = 22, scale = 5)
private BigDecimal prrdAnnualPrem;

/**
 * Risk cover days
 */
@Column(name = "PRRD_COVER_DAYS", precision = 5)
private Long prrdCoverDays;

/**
 * Risk prorata premium
 */
@Column(name = "PRRD_PRORATA_PREM", precision = 22, scale = 5)
private BigDecimal prrdProrataPrem;

/**
 * Previous net retention
 */
@Column(name = "PRRD_PREV_NET_RETENTION", precision = 22, scale = 5)
private BigDecimal prrdPrevNetRetention;

/**
 * Net refund premium
 */
@Column(name = "PRRD_REFUND_NET_PREM", precision = 22, scale = 5)
private BigDecimal prrdRefundNetPrem;

/**
 * Facre refund premium
 */
@Column(name = "PRRD_REFUND_FACRE_PREM", precision = 22, scale = 5)
private BigDecimal prrdRefundFacrePrem;

/**
 * Net reinsurance premium
 */
@Column(name = "PRRD_NET_PREM", precision = 22, scale = 5)
private BigDecimal prrdNetPrem;

/**
 * Previous transaction code referencing GIN\_POLICY\_RISK\_DTLS.PRRD\_CODE
 */
@Column(name = "PRRD_PREV_PRRD_CODE", precision = 22)
private Long prrdPrevPrrdCode;

/**
 * Foreign Key referencing GIN\_ARRANGEMENT\_SETUPS.as\_code
 */
@Column(name = "PRRD_AS_CODE", precision = 22)
private Long prrdAsCode;

/**
 * Earthquake premium
 */
@Column(name = "PRRD_EARTHQUAKE_PREM", precision = 35, scale = 5)
private BigDecimal prrdEarthquakePrem;

/**
 * Reinsurance net less earthquake premium
 */
@Column(name = "PRRD_RI_NET_LESS_EQ_PREM", precision = 35, scale = 5)
private BigDecimal prrdRiNetLessEqPrem;

    /**
 * Foreign Key referencing GIN_TREATY_ARRANGEMENTS.TA_CODE
 */
@Column(name = "PRRD_TA_CODE", precision = 22)
private Long prrdTaCode;

/**
 * Net previous premium
 */
@Column(name = "PRRD_NET_PREV_PREM", precision = 22, scale = 5)
private BigDecimal prrdNetPrevPrem;

/**
 * Reinsurance previous premium amount
 */
@Column(name = "PRRD_RI_PREV_PREM", precision = 22, scale = 5)
private BigDecimal prrdRiPrevPrem;

/**
 * Reinsurance Sum insured
 */
@Column(name = "PRRD_RI_SI", precision = 23, scale = 5)
private BigDecimal prrdRiSi;

/**
 * Previous reinsurance sum insured
 */
@Column(name = "PRRD_PREV_RI_SI", precision = 23, scale = 5)
private BigDecimal prrdPrevRiSi;

/**
 * Facre obligatory excess amount
 */
@Column(name = "PRRD_FACOBLIG_EXCESS", precision = 22, scale = 5)
private BigDecimal prrdFacobligExcess;

/**
 * Facre obligatory limit amount
 */
@Column(name = "PRRD_FACOBLIG_LIMIT", precision = 22, scale = 5)
private BigDecimal prrdFacobligLimit;

/**
 * Facre obligatory user specified amount
 */
@Column(name = "PRRD_FACOBLIG_USER_EXCESS", precision = 23, scale = 5)
private BigDecimal prrdFacobligUserExcess;

/**
 * Special company retention amount
 */
@Column(name = "PRRD_SPECIAL_COMP_RETENTION", precision = 22)
private Long prrdSpecialCompRetention;

/**
 * Premium Difference
 */
@Column(name = "PRRD_PREM_DIFF", precision = 23, scale = 2)
private BigDecimal prrdPremDiff;

/**
 * Indicates if Facre obligatory is to be applied
 */
@Column(name = "PRRD_FACOBLIG_ALLOC_CHK", length = 1)
private String prrdFacobligAllocChk;

/**
 * Indicates if reinsurance pool is to be applied or not
 */
@Column(name = "PRRD_CEDE_POOL", length = 1)
private String prrdCedePool;

    /**
     * The effective date for the record.
     */
    @Column(name = "PRRD_EFFECTIVE_DATE")
    private Date prrdEffectiveDate;

    /**
     * The gross company retention type.
     * The value is a single-character string.
     */
    @Column(name = "PRRD_GROSS_CMP_RET_TYPE", length = 1)
    private String prrdGrossCmpRetType;

    /**
     * Indicates whether the reinsurance is reinsured.
     * The value is a single-character string (e.g., 'Y' for Yes, 'N' for No).
     */
    @Column(name = "PRRD_RI_REINSURED", length = 1)
    private String prrdRiReinsured;

    /**
     * The previous facre (facultative reinsurance) premium amount.
     * The value has a precision of 23 and a scale of 4.
     */
    @Column(name = "PRRD_PREV_FACRE_PREM", precision = 23, scale = 4)
    private BigDecimal prrdPrevFacrePrem;

    /**
     * The cumulative reinsurance premium.
     * The value has a precision of 23 and a scale of 4.
     */
    @Column(name = "PRRD_CUMM_RI_PREM", precision = 23, scale = 4)
    private BigDecimal prrdCummRiPrem;

    /**
     * Indicates whether the company retention amount was edited.
     * The value is a single-character string.
     */
    @Column(name = "PRRD_COMP_RET_EDITED", length = 1)
    private String prrdCompRetEdited;

    /**
     * The previous facre (facultative reinsurance) sum insured amount.
     * The value has a precision of 23 and a scale of 4.
     */
    @Column(name = "PRRD_PREV_FACRE_SI", precision = 23, scale = 4)
    private BigDecimal prrdPrevFacreSi;

    /**
     * The VLMP (very large maximum possible) excess premium.
     * The value has a precision of 20 and a scale of 5.
     */
    @Column(name = "PRRD_VLMP_EXCESS_PREM", precision = 20, scale = 5)
    private BigDecimal prrdVlmpExcessPrem;

    /**
     * The VLMP (very large maximum possible) excess sum insured.
     * The value has a precision of 20 and a scale of 5.
     */
    @Column(name = "PRRD_VLMP_EXCESS_SI", precision = 20, scale = 5)
    private BigDecimal prrdVlmpExcessSi;

}
